[project]
name = "poi-sim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "nbdime>=4.0.2",
    "nbstripout>=0.8.2",
    "pandas>=2.3.3",
]
